Crud_Shop/Crud_Shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import home

from accounts.views import login_view, register_view, logout_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profiles/', include('accounts.urls', namespace='accounts')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^Crud_Shop/', include('shopping_cart.urls', namespace='shopping_cart')),
    url(r'^home', home),
    url(r'^accounts/login', login_view),
    url(r'^accounts/register', register_view),
    url(r'^accounts/logout', logout_view)

]

Crud_Shop/accounts/urls.py
from django.conf.urls import url

from .views import my_profile

app_name = 'accounts'

urlpatterns = [
	url(r'^me/$', my_profile, name='my_profile')
]


Crud_Shop/products/urls.py
from django.conf.urls import url

from .views import product_list

app_name = 'products'

urlpatterns = [
    url(r'^', product_list, name='product-list')
]

Crud_Shop/shopping_cart/urls.py
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    process_payment,
    update_transaction_records,
    success
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-Crud_Shop/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^payment/(?P<order_id>[-\w]+)/$', process_payment, name='process_payment'),
    url(r'^update-transaction/(?P<order_id>[-\w]+)/$', update_transaction_records,
        name='update_records')
]

Crud_Shop/products/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=120)
    price = models.IntegerField()

    def __str__(self):
        return self.name

Crud_Shop/products/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from shopping_cart.models import Order
from .models import Product


#This function is used to get all the products that have been purchased by a user.
#first it gets all the product objects then filters them by the products that exists within the user profile
#This is to get all the products that are availble to the user and filter the ones the user already owns
def product_list(request):
    object_list = Product.objects.all()
    filtered_orders = Order.objects.filter(owner=request.user.profile, is_ordered=False)
    current_order_products = []
    if filtered_orders.exists():
    	user_order = filtered_orders[0]
    	user_order_items = user_order.items.all()
    	current_order_products = [product.product for product in user_order_items]

    context = {
        'object_list': object_list,
        'current_order_products': current_order_products
    }

    return render(request, "products/product_list.html", context)

Crud_Shop/products/templates/products/product_list.html
{% extends 'base.html' %}

{% block content %}
<h1 align="center">School Book Store</h1>
    {{ message }}
<div class="row">
    {% for object in object_list %}
</div>
<div class="row" align="center">
    <div class="col-sm-3" ; style="border: 5px solid">
        <p>{{ object.name }}</p>
        <p>Price: ${{ object.price }}</p>
        {% if object in user.profile.ebooks.all %}
        This book is already owned by you
        {% elif object in current_order_products %}
        <a href="{% url 'shopping_cart:order_summary' %}" class="btn btn-primary">Go to Cart</a>
        {% else %}
        <a href="{% url 'shopping_cart:add_to_cart' object.id %}" class="btn-primary">Add to Cart</a>
        {% endif %}
    </div>
    {% endfor %}
</div>
{% endblock content %}