Crud_Shop/Crud_Shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import home

from accounts.views import login_view, register_view, logout_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profiles/', include('accounts.urls', namespace='accounts')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^Crud_Shop/', include('shopping_cart.urls', namespace='shopping_cart')),
    url(r'^home', home),
    url(r'^accounts/login', login_view),
    url(r'^accounts/register', register_view),
    url(r'^accounts/logout', logout_view)

]

Crud_Shop/accounts/urls.py
from django.conf.urls import url

from .views import my_profile

app_name = 'accounts'

urlpatterns = [
	url(r'^me/$', my_profile, name='my_profile')
]


Crud_Shop/products/urls.py
from django.conf.urls import url

from .views import product_list

app_name = 'products'

urlpatterns = [
    url(r'^', product_list, name='product-list')
]

Crud_Shop/shopping_cart/urls.py
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    process_payment,
    update_transaction_records,
    success
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-Crud_Shop/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^payment/(?P<order_id>[-\w]+)/$', process_payment, name='process_payment'),
    url(r'^update-transaction/(?P<order_id>[-\w]+)/$', update_transaction_records,
        name='update_records')
]

Crud_Shop/shopping_cart/models.py
from __future__ import unicode_literals

from django.db import models

from accounts.models import Profile
from products.models import Product


class OrderItem(models.Model):
    product = models.OneToOneField(Product, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return self.product.name


class Order(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.price for item in self.items.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)

Crud_Shop/shopping_cart/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404

from accounts.models import Profile
from products.models import Product

from shopping_cart.extras import generate_order_id
from shopping_cart.models import OrderItem, Order


def get_user_pending_order(request):
    # get order for the correct user
    user_profile = get_object_or_404(Profile, user=request.user)
    order = Order.objects.filter(owner=user_profile, is_ordered=False)
    if order.exists():
        # get the only order in the list of filtered orders
        return order[0]
    return 0


@login_required()
def add_to_cart(request, **kwargs):
    # get the user profile
    user_profile = get_object_or_404(Profile, user=request.user)
    # filter products by id
    product = Product.objects.filter(id=kwargs.get('item_id', "")).first()
    # check if the user already owns this product
    if product in request.user.profile.ebooks.all():
        messages.info(request, 'You already own this ebook')
        return redirect(reverse('products:product-list')) 
    # create orderItem of the selected product
    order_item, status = OrderItem.objects.get_or_create(product=product)
    # create order associated with the user
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        # generate a reference code
        user_order.ref_code = generate_order_id()
        user_order.save()

    # show confirmation message and redirect back to the same page
    messages.info(request, "item added to Crud_Shop")
    return redirect(reverse('products:product-list'))

@login_required()
def delete_from_cart(request, item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Item has been deleted")
    return redirect(reverse('shopping_cart:order_summary'))


@login_required()
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order
    }
    return render(request, 'shopping_cart/order_summary.html', context)


@login_required()
def checkout(request):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order,
    }
    return render(request, 'shopping_cart/checkout.html', context)


@login_required()
def process_payment(request, order_id):
    # process the payment
    return redirect(reverse('shopping_cart:update_records',
                    kwargs={
                        'order_id': order_id,
                    })
                )


@login_required()
def update_transaction_records(request, order_id):
    # get the order being processed
    order_to_purchase = Order.objects.filter(pk=order_id).first()

    # update placed order
    order_to_purchase.is_ordered=True
    order_to_purchase.date_ordered=datetime.datetime.now()
    order_to_purchase.save()
    
    # get all items in the order - generates a queryset
    order_items = order_to_purchase.items.all()

    # update order items
    order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())

    # Add products to user profile
    user_profile = get_object_or_404(Profile, user=request.user)
    # get the products from the items
    order_products = [item.product for item in order_items]
    user_profile.ebooks.add(*order_products)
    user_profile.save()

    #====== TODO: Update Payment records ========

    # send an email to the customer
    messages.info(request, "Thank you! Your items have been added to your profile")
    return redirect(reverse('accounts:my_profile'))


def success(request, **kwargs):
    # a view signifying the transcation was successful
    return render(request, 'shopping_cart/purchase_success.html', {})

Crud_Shop/shopping_cart/templates/shopping_cart/checkout.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<style>
    table.borderless td,table.borderless th{
       border: none !important;
    }
</style>

 <section>
    <div class="row" id="tablerow">

    <div class="col-md-8 col-xs-12">
      <table class="table">
        <tr>
          <td><h4>Order Summary</h4></td>
        </tr>
        <tr>
          <td>
            {% for item in order.get_cart_items %}
              <tr>
                <td>{{ item }}</td>
                <td>$ {{ item.product.price }}</td>
              </tr>
            {% endfor %}
          </td>
        </tr>
        <tr>
          <td><strong>Order Total</strong> </td>
          <td> <strong>$ {{ order.get_cart_total }}</strong></td>
        </tr>
      </table>
        <form method="POST" action="{% url 'shopping_cart:process_payment' order.id %}">
          {% csrf_token %}
          <button style="width: 50%; float: left;" class="btn btn-warning">Complete Purchase</button>

        </form>
    </div>
   </div>
 </section>
{% endblock content %}

{% block scripts %}
  {{ block.super }}

  <!-- initialize jQuery Library -->
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Bootstrap jQuery -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
      
{% endblock scripts %}

Crud_Shop/shopping_cart/templates/shopping_cart/order_summary.html
{% extends "base.html" %}

{% block content %}

 <section>
   <h1 align="center">This is your shopping cart!</h1>
   <div class="row">
    <table class="table table-hover table-bordered text-center">
      <tr class="text-center">

        <th>Item</th>
        <th>Price</th>
      </tr>
      {% for item in order.get_cart_items %}
        <tr>

          <td>
            {{ item.product.name }}
            <span class="pull-right">

            </span>
          </td>
          <td>{{ item.product.price }}</td>
          <td><a href="{% url 'shopping_cart:delete_item' item.id %}" data-balloon="remove this item from cart" class="text-danger" onclick="return confirm_delete();">
                <i class="fas fa-trash"></i>
              </a></td>
        </tr>
      {% empty %}
        <tr>
          <td colspan= 3> You have not added any items yet.</td>
        </tr>
      {% endfor %}
      <tr>
        {% if order.get_cart_total != None %}
        <td colspan=1>
          <strong class="pull-right">Order Total:</strong>
        </td>

        <td colspan=1>
          $<strong>{{ order.get_cart_total }}</strong>
        </td>
        {% endif %}
      </tr>
      <tr>
        <td colspan=1 >
          <a href="{% url 'products:product-list' %}" class="btn btn-warning pull-left">
            {% if order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a>
        </td>
        <td colspan=1>
          {% if order.get_cart_items %}
            <a href="{% url 'shopping_cart:checkout' %}" class="pull-right btn btn-primary">Proceed To Checkout</a>
          {% endif %}
        </td>
      </tr>
    </table>
     
   </div>
 </section>
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script>
  function confirm_delete(){
    return confirm("Do you want to remove this item from cart?");
  }
  </script>
{% endblock scripts %}

Crud_Shop/shopping_cart/templates/shopping_cart/purchase_success.html
{% extends 'base.html' %}

{% block content %}
    <h1> Purchase Complete!</h1>
    <a href="{% url 'products:product-list' %}">Head back home</a>
{% endblock content %}