Crud_Shop/Crud_Shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import home

from accounts.views import login_view, register_view, logout_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profiles/', include('accounts.urls', namespace='accounts')),
    url(r'^products/', include('products.urls', namespace='products')),
    url(r'^Crud_Shop/', include('shopping_cart.urls', namespace='shopping_cart')),
    url(r'^home', home),
    url(r'^accounts/login', login_view),
    url(r'^accounts/register', register_view),
    url(r'^accounts/logout', logout_view)

]

Crud_Shop/accounts/urls.py
from django.conf.urls import url

from .views import my_profile

app_name = 'accounts'

urlpatterns = [
	url(r'^me/$', my_profile, name='my_profile')
]


Crud_Shop/products/urls.py
from django.conf.urls import url

from .views import product_list

app_name = 'products'

urlpatterns = [
    url(r'^', product_list, name='product-list')
]

Crud_Shop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cart</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
</head>
<body>
    <div class="container">
    	{% include 'messages.html' %}
        {% block content %}{% endblock content %}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
</body>
</html>

Crud_Shop/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> </title>
</head>
<body>
<h1>Home Page</h1>
</body>
</html>

Crud_Shop/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit"/>
    </form>
</body>
</html>

Crud_Shop/templates/messages.html
{% if messages %}

 	<style type="text/css">
 		div.messages{
 			background-color: #ff6b6b;
 			color: #f7fff7;
 		}
 		ul.messages{
 			list-style-type: none;
 		}
 	</style>

    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

Crud_Shop/templates/profile.html
{% extends 'base.html' %}

{% block content %}

<table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>Date Ordered</th>
        <th>Reference Code</th>
        <th>Items</th>
        <th>Price</th>
      </tr>
      {% for order in my_orders %}
        <tr>
          <td>{{ order.date_ordered }}</td>
          <td>{{ order.ref_code }}</td>
          <td>
        	{% for item in order.items.all %}
        		{{ item.product.name }}
      		{% endfor %}
      	  </td>
          <td>${{ order.get_cart_total }}</td>

        </tr>
      {% empty %}
        <tr>
          <td colspan= 4> You have no orders.</td>
        </tr>
      {% endfor %}

      <tr>
        <td colspan=4>
          <a href="{% url 'products:product-list' %}" class="btn btn-warning pull-left">
            {% if not order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a>
        </td>
      </tr>
    </table>

{% endblock content %}

Crud_Shop/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit"/>
    </form>



</body>
</html>